### PR TITLE
Fix Addition and Editing of Identical Foods

### LINKED ISSUE #270: Case sensitive issue
Add command adds the same food item when the exact inputs are added but with upper case. Suggest making the check for duplicate food items case insensitive. 

<hr><sub>[original: Kzrthikz/ped#1]<br/>
</sub>

### PR DESCRIPTION
**Pull request by seanlowjk**
Changes the `equals` and `isSameFood` method to depend on the Food's name only. 

This is to prevent an incident where the user does 

either: 
`add n/Chicken Rice p/3.00 c/Chinese` 
`add n/chIcKen Rice p/3.00 c/Chinese` 

OR 

`add n/Chicken Rice p/3.00 c/Chinese` 
`add n/Fried Rice p/3.00 c/Chinese` 
`edit 2 n/Chicken Rice`

This PR Fixes #270

### CODE REVIEW

File: src/main/java/seedu/savenus/model/food/Food.java [hunk 1]
```diff
@@ -147,13 +141,10 @@ public boolean equals(Object other) {
...
-                && otherFood.getDescription().equals(getDescription())
-                && otherFood.getTags().equals(getTags())
-                && otherFood.getCategory().equals(getCategory())
-                && otherFood.getLocation().equals(getLocation())
-                && otherFood.getOpeningHours().equals(getOpeningHours())
-                && otherFood.getRestrictions().equals(getRestrictions());
+                && (otherFood.getDescription().equals(getDescription())
+                        && otherFood.getLocation().equals(getLocation())
+                        && otherFood.getRestrictions().equals(getRestrictions())
+                        && otherFood.getOpeningHours().equals(getOpeningHours()));
```
Comment (fatclarence) [inline src/main/java/seedu/savenus/model/food/Food.java]: Remember to include into your Design Considerations in the Developer Guide why you dictate these to deem the foods as equals.

**Comment by fatclarence** [comment]
Left a comment on your fixes. Catches the instances of duplicate foods even when I add and tried to edit the food item to be identical to another. Great considerations. Do update the Developer Guide as stated
